export enum categoryActionTypes {
  OPEN_ADD_CATEGORY_MODAL = '[Category] Open add category modal',
  CLOSE_ADD_CATEGORY_MODAL = '[Category] Close add category modal',
  GET_CATEGORIES = '[Category] Get categories',
  GET_CATEGORIES_SUCCESS = '[Category] Get categories success',
  GET_CATEGORIES_FAIL = '[Category] Get categories fail',
  OPEN_DELETE_CATEGORY_MODAL = '[Delete Category Modal] Delete category modal',
  CLOSE_DELETE_CATEGORY_MODAL = '[Delete Category Modal] Close category modal',
  DELETE_CATEGORY = '[Delete Category Modal] Delete category',
  DELETE_CATEGORY_SUCCESS = '[Delete Category Modal] Delete category success',
  DELETE_CATEGORY_FAIL = '[Delete Category Modal] Delete category fail',
  OPEN_EDIT_CATEGORY_MODAL = '[Edit Category Modal] Open edit category modal',
  CLOSE_EDIT_CATEGORY_MODAL = '[Edit Category Modal] Close edit category modal',
  FILTER_BY_CATEGORY_FROM_INPUT = '[Add Category Form] Filter by category from input',
  FILTER_BY_CATEGORY_FROM_SELECT = '[Add Category Form] Filter by category from select',
}
