export enum staffActionTypes {
  GET_STAFF = '[Staff] Get staff',
  GET_STAFF_SUCCESS = '[Staff] Get staff success',
  GET_STAFF_FAIL = '[Staff] Get staff fail',
  FILTER_STAFF_BY_NAME = '[Add and Search Staff] Filter staff by name',
  FILTER_STAFF_BY_ROLE = '[Add and Search Staff] Filter staff by role',
  OPEN_ADD_STAFF_MODAL = '[Add Staff Modal] Add staff modal',
  CLOSE_STAFF_MODAL = '[Close Staff Modal] Close staff modal',
  OPEN_DELETE_STAFF_MODAL = '[Staff member] Open delete staff modal',
  CLOSE_DELETE_STAFF_MODAL = '[Staff] Close delete staff modal',
  DELETE_STAFF_RECORD = '[Staff] Delete staff record',
  DELETE_STAFF_SUCCESS = '[Staff] delete staff success',
  DELETE_STAFF_FAIL = '[Staff] Delete staff fail',
  OPEN_EDIT_STAFF_MODAL = '[Staff Member] Open edit staff modal',
  CLOSE_EDIT_STAFF_MODAL = '[Edit Staff] Close edit staff modal',
}
