export enum productActionTypes {
  GET_PRODUCTS = '[Products] Get Products',
  GET_PRODUCTS_SUCCESS = '[Products] Get products success',
  GET_PRODUCTS_FAIL = '[Products] Get products fail',
  OPEN_PRODUCT_MODAL = '[Products] Open products modal',
  OPEN_EDIT_PRODUCT_MODAL = '[Products] Open edit product modal',
  CLOSE_EDIT_PRODUCT_MODAL = '[Products] Close edit product modal',
  CLOSE_PRODUCT_MODAL = '[Products] Close products modal',
  ADD_PRODUCT = '[Products] Add Product',
  ADD_PRODUCT_SUCCESS = '[Products] Add product success',
  ADD_PRODUC_FAIL = '[Products] Add product fail',
  EDIT_PRODUCT = '[Products] Edit product',
  EDIT_PRODUCT_SUCCESS = '[Products] Edit product success',
  EDIT_PRODUCT_FAIL = '[Products] Edit product fail',
}
