export enum productActionTypes {
  GET_PRODUCTS = '[Products List] Get Products',
  GET_PRODUCTS_SUCCESS = '[Products List] Get products success',
  GET_PRODUCTS_FAIL = '[Products List] Get products fail',
  OPEN_PRODUCT_MODAL = '[Add product modal] Open products modal',
  OPEN_EDIT_PRODUCT_MODAL = '[Edit product modal] Open edit product modal',
  CLOSE_EDIT_PRODUCT_MODAL = '[Edit product modal] Close edit product modal',
  CLOSE_PRODUCT_MODAL = '[Add product modal] Close products modal',
  ADD_PRODUCT = '[Add Product modal] Add Product',
  ADD_PRODUCT_SUCCESS = '[Add product modal] Add product success',
  ADD_PRODUC_FAIL = '[Add product modal] Add product fail',
  EDIT_PRODUCT = '[Edit product modal] Edit product',
  EDIT_PRODUCT_SUCCESS = '[Edit product modal] Edit product success',
  EDIT_PRODUCT_FAIL = '[Product Filter] Edit product fail',
  FILTER_PRODUCTS_BY_NAME = '[Product Filter] Filter products by name',
  FILTER_PRODUCTS_BY_CATEGORY = '[Product Filter] Filter products by category',
  FILTER_BY_ORDER = '[Product Filter]Filter products by order',
  TOOGLE_PUBLISH_PRODUCT = '[Product Item] Toggle publish product',
  TOOGLE_PUBLISH_PRODUCT_SUCCESS = '[Product Item] Toggle publish product success',
  TOOGLE_PUBLISH_PRODUCT_FAIL = '[Product Item] Toggle publish product fail',
  SET_PUBLISH_PRODUCT_STATUS_TO_DEFAULT = '[Product Item] Set publish product status to default',
}
