export enum couponsActionTypes {
  GET_COUPONS = '[Coupons] Get coupons',
  GET_COUPONS_SUCCESS = '[Coupons] Get coupns success',
  GET_COUPONS_FAIL = '[Coupns] Get coupns fail',
  FILTER_COUPONS_BY_NAME = '[Add and Search Coupons] Filter coupns by name',
  CLOSE_ADD_COUPON_MODAL = '[Add coupon modal] Close add coupon modal',
  OPEN_ADD_COUPON_MODAL = '[Add coupon modal] Open add coupon modal',
  CLOSE_EDIT_COUPON_MODAL = '[Edit coupon modal] Close edit coupon modal',
  OPEN_EDIT_COUPON_MODAL = '[Edit coupon modal] Open edit coupon modal',
  OPEN_DELETE_COUPON_MODAL = '[Coupon] Open delete coupon modal',
  CLOSE_DELETE_COUPON_MODAL = '[Coupon] Close delete coupon modal ',
  DELETE_COUPON = '[Coupons] Delete coupon',
  DELETE_COUPON_SUCCESS = '[Coupons] Delete coupon success',
  DELETE_COUPON_FAILED = '[Coupons] Delete coupon failed',
}
